myName = input("what's your name?")
myLunch = input("what are you having for lunch?")
print(myName,"is going to be chowing down on",myLunch,"very soon!")
print("#"*15)
print()
number = input("give me a number: ")
group = input("give a collective noun for a group of things: ")
thing = input("give me the name of a weird or wacky thing: ")
print("No I don´t think that", number, "is a", group, "of", thing, ". Thats just odd")

name_food = input("Enter the name of a food: ")
name_plant = input("Enter a type of plant ")
method_cooking = input("Enter a method of cooking ")
word = input("what word describes a great food ")
item = input("name a DIY item ")
dessert = input("favourite dessert")
print()
print("#"*7)
print("MENU")
print("#"*7)
print("saute",name_food,"with",word,name_plant,"on a bed of ",item)
print("""
and for the dessert 
[III]
""", dessert)
