print("=== your're adventure simulator ===")
print("You'll be asked a bunch of questions then we'll make you up an amazing history  \U0001F389")
print()
name = input("Enter your name ")
enemy = input("Enter your enemy name ")
super_power = input("your super power: ")
print()
print("\033[35m'here we go!'\033[0m ")
print(f"Our story begins here, as {name} approaches a big castle")
print(f"suddenly a storm and a bolt of fire strike the ground at the feet of super {name}")
print(f"Our final fight begins shout {enemy}, clearly missing the fact that {name} has the power of {super_power}, \033[32m'which means he'll win quickly'\033[0m")
